# Generated by Django 6.0.3 on 2026-03-06 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='asset',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('mac', models.CharField(max_length=50)),
            ],
        ),
    ]
